version: 2

sources:
  - name: raw
    database: olist_warehouse
    schema: raw
    tables:
      - name: orders
      - name: order_items
      - name: customers
      - name: products
      - name: sellers
      - name: order_payments
      - name: order_reviews
      - name: product_category_name_translation
      - name: geolocation
    